### ISSUE TITLE
Can we get HD UI textures somehow?

### ISSUE THREAD

**Issue by Nikita-S-Doroshenko** [Gethe/wow-ui-textures#1]
Just take a look in to new WoW App UI - their textures are amazing, it's high definition, and then compare it with WoW UI (blurred UI).

I'm playing on 4K display, and WoW's UI looks so terrible, so blurred, but still I like it a lot better then some fancy-shmancy minimalist or space UI styles.

Can blizzard give us PSD files or UHD files of their UI elements, so we can replace existing ones?

**Comment by Gethe** [comment]
These aren't texture replacements, it's literally just a dump of the textures Blizzard uses.
