### ISSUE TITLE
convert all files in one go

### ISSUE THREAD

**Issue by Goten87** [Gethe/wow-ui-textures#2]
hello how do u convert all the files in the interface folder in one go 
i have bin trying to do this for like 3 days now and i have no clue how to do it
i have tryed 2 programs now (CMD only)
and the first had a option `-o` to set a compleet folder (dint work at all)
so how are u doing that

**Comment by Gethe** [comment]
I use BLPc, link is in the readme. It is a GUI app and has a batch convert option.

**Comment by Goten87** [comment]
hmmm oke
so will that put the png files in a new folder or do u need to seperate them your self

**Comment by Gethe** [comment]
By default it will put the new file in the same folder, but you can choose another.
