### ISSUE TITLE
Can't Download the zip file

### ISSUE THREAD

**Issue by Ridimo** [Gethe/wow-ui-textures#3]
Heya, 

i can't download the zip file to add it to my interface folder. Always tells me that the zip file is corrupted with wrong end of file. Is there a way to dl everything ?

Thanks in advance.

**Comment by IrcDirk** [comment]
Just checked, works for me, no problems. Im using 7zip. Maybe your download was interupted? The file is about ~2,4GB so u should check if u have the whole file.

**Comment by Ridimo** [comment]
Thanks for the reply !

Yeah i don't get 2.4gb at all ! the direct download gives me a file of ~100Mo and even if i have 500Mo connexion the download speed is at 50ko max !

is there a way to get the files ?

And how should i use them once downloaded ? put the folders in the /wow/interface/ ?

thanks in advance dude ^^

**Comment by Marie-Donnie** [comment]
If there is a problem with the zip file, you can also clone the repository with `git clone https://github.com/Gethe/wow-ui-textures.git` if you are on Linux and have git installed.
If you are on windows, you can also download Github client https://desktop.github.com/ to get the entire repository.

For the "how" you should use them, it depends on what you want to do with them; I don't think it is meant to be used as a replacement for WoW files.

**Comment by Ridimo** [comment]
thnx for the help with the repository thingy !

So it's not used as textures to place them in wow/interface folder in order to change "original" wow textures ? used for like make the defaukt UI more darker without being an addon ?

**Comment by IrcDirk** [comment]
These are orginal wow textures dumped from the game ;)

**Comment by Ridimo** [comment]
OHHHHH well ! okay ^^ 

i misunderstood then....i feel really dumb :(

sorry dude and thanks a lot for your time :D
