### ISSUE TITLE
Potential file name changes?

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Gethe/wow-ui-textures#5]
Im trying to do some edits on the microbar icons, however using the filenames provided in the "Buttons" folder inside the zip does not work.

Would it be possible to check if these have changed?

**Comment by Gethe** [comment]
In BfA they moved all the micro button textures to https://github.com/Gethe/wow-ui-textures/blob/live/MainMenuBar/MainMenuBar.PNG

**Comment by Jin-Jiyunsun** [comment]
cool. thanks
