### ISSUE TITLE
Files changed, no longer line up with current patch 9.1.5

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Gethe/wow-ui-textures#6]
I know of one file that has almost completly changed in structure, https://github.com/Gethe/wow-ui-textures/blob/live/MainMenuBar/MainMenuBar.PNG.

The image in the file which is from i think 9.0.2 no longer matches up with what 9.1.5 displays it as, this is what my micro bar looks like now
![brokenmicrobar](https://user-images.githubusercontent.com/37377657/145066245-5f426e44-fc75-481f-bbd2-c069197831c9.png)

**Comment by Gethe** [comment]
Noted, though this repo isn't intended to be used as a direct texture replacement.
